# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=50)),
                ('max_size', models.IntegerField(default='10000000000')),
                ('mode', models.CharField(choices=[('T', 'time'), ('S', 'size')], default='T', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
