# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 23:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0002_basket_delta_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smt', models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='Audio', max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('is_directory', models.BooleanField(default=False)),
                ('is_recursive', models.BooleanField(default=False)),
                ('basket_path', models.CharField(max_length=50)),
                ('regexp', models.CharField(max_length=30)),
                ('restorename', models.CharField(max_length=30)),
                ('is_merge', models.BooleanField(default=None)),
                ('is_replace', models.BooleanField(default=None)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='delta_time',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
        migrations.AlterField(
            model_name='basket',
            name='max_size',
            field=models.IntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='path',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
