# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0003_auto_20170614_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_directory',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_merge',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_recursive',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_replace',
        ),
        migrations.RemoveField(
            model_name='task',
            name='path',
        ),
        migrations.RemoveField(
            model_name='task',
            name='smt',
        ),
        migrations.AddField(
            model_name='task',
            name='params',
            field=models.CharField(choices=[('Remove params', (('f', 'file'), ('d', 'empty directory'), ('r', 'nor empty directory'))), ('Restore params', (('m', 'merge'), ('r', 'replace')))], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='path_to_removing_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.CharField(choices=[('RM', 'remove'), ('RS', 'restore')], default='remove', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='regexp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='restorename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
