# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0004_auto_20170614_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
    ]
