# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0006_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_alive',
        ),
    ]
