# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0007_remove_task_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.CharField(default='result', max_length=100),
        ),
    ]
