# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0010_auto_20170615_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
