# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0013_task_is_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
    ]
