# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaskets', '0014_auto_20170617_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
